apple_test_set = [

# ========================
# Core Revenue
# ========================
{
    "question": "What is Apple's total net sales for the twelve months ended September 27, 2025?",
    "answer": "$416,161 million"
},

{
    "question": "What is Apple's total net sales for the three months ended September 27, 2025?",
    "answer": "$102,466 million"
},

{
    "question": "What is Apple's product revenue for 2025?",
    "answer": "$307,003 million"
},

{
    "question": "What is Apple's services revenue for 2025?",
    "answer": "$109,158 million"
},

# ========================
# Product Categories
# ========================
{
    "question": "What is iPhone revenue for 2025?",
    "answer": "$209,586 million"
},

{
    "question": "What is Mac revenue for 2025?",
    "answer": "$33,708 million"
},

{
    "question": "What is iPad revenue for 2025?",
    "answer": "$28,023 million"
},

{
    "question": "What is Wearables, Home and Accessories revenue for 2025?",
    "answer": "$35,686 million"
},

# ========================
# Profitability
# ========================
{
    "question": "What is Apple's gross margin for 2025?",
    "answer": "$195,201 million"
},

{
    "question": "What is Apple's operating income for 2025?",
    "answer": "$133,050 million"
},

{
    "question": "What is Apple's net income for 2025?",
    "answer": "$112,010 million"
},

# ========================
# Expenses
# ========================
{
    "question": "What is Apple's research and development expense for 2025?",
    "answer": "$34,550 million"
},

{
    "question": "What is Apple's selling, general and administrative expense for 2025?",
    "answer": "$27,601 million"
},

# ========================
# Geography
# ========================
{
    "question": "What is Apple's revenue in the Americas for 2025?",
    "answer": "$178,353 million"
},

{
    "question": "What is Apple's revenue in Europe for 2025?",
    "answer": "$111,032 million"
},

{
    "question": "What is Apple's revenue in Greater China for 2025?",
    "answer": "$64,377 million"
},

{
    "question": "Which region has the highest revenue for Apple in 2025?",
    "answer": "Americas"
},

# ========================
# Balance Sheet
# ========================
{
    "question": "What is Apple's total assets as of September 27, 2025?",
    "answer": "$359,241 million"
},

{
    "question": "What is Apple's total liabilities as of September 27, 2025?",
    "answer": "$285,508 million"
},

{
    "question": "What is Apple's total shareholders' equity in 2025?",
    "answer": "$73,733 million"
},

{
    "question": "What is Apple's cash and cash equivalents in 2025?",
    "answer": "$35,934 million"
},

# ========================
# Cash Flow
# ========================
{
    "question": "What is Apple's net cash generated by operating activities in 2025?",
    "answer": "$111,482 million"
},

{
    "question": "What is Apple's net cash used in financing activities in 2025?",
    "answer": "$-120,686 million"
},

{
    "question": "What is Apple's ending cash balance in 2025?",
    "answer": "$35,934 million"
},

# ========================
# Reasoning Questions (Important)
# ========================
{
    "question": "What is the difference between total net sales in 2025 and 2024?",
    "answer": "$25,126 million"
},

{
    "question": "Which product category generates the highest revenue?",
    "answer": "iPhone"
},

{
    "question": "What percentage of total revenue comes from services?",
    "answer": "approximately 26%"
},

{
    "question": "Is Apple's net income higher in 2025 compared to 2024?",
    "answer": "Yes"
},

]